// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYSSmZSvuhMV4VmNmqLm_0RVUmh_9OLMk',
    appId: '1:671884374717:web:74df6cf0f9584e48813dd4',
    messagingSenderId: '671884374717',
    projectId: 'pantrypal-fcf83',
    authDomain: 'pantrypal-fcf83.firebaseapp.com',
    storageBucket: 'pantrypal-fcf83.firebasestorage.app',
    measurementId: 'G-ZPNYJ3QS9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAlwUiEINd1dpziVdX5Z132MDiHg199ew',
    appId: '1:671884374717:android:4deaf8b9c7133f7b813dd4',
    messagingSenderId: '671884374717',
    projectId: 'pantrypal-fcf83',
    storageBucket: 'pantrypal-fcf83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bQlt_JeEJ7IcuYFzlvK2KmqMLrQyTdA',
    appId: '1:671884374717:ios:631cbc3263b80f00813dd4',
    messagingSenderId: '671884374717',
    projectId: 'pantrypal-fcf83',
    storageBucket: 'pantrypal-fcf83.firebasestorage.app',
    iosBundleId: 'com.example.pantrypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bQlt_JeEJ7IcuYFzlvK2KmqMLrQyTdA',
    appId: '1:671884374717:ios:631cbc3263b80f00813dd4',
    messagingSenderId: '671884374717',
    projectId: 'pantrypal-fcf83',
    storageBucket: 'pantrypal-fcf83.firebasestorage.app',
    iosBundleId: 'com.example.pantrypal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYSSmZSvuhMV4VmNmqLm_0RVUmh_9OLMk',
    appId: '1:671884374717:web:5792e9fc4558081d813dd4',
    messagingSenderId: '671884374717',
    projectId: 'pantrypal-fcf83',
    authDomain: 'pantrypal-fcf83.firebaseapp.com',
    storageBucket: 'pantrypal-fcf83.firebasestorage.app',
    measurementId: 'G-43DK4ZW3EF',
  );
}
